[profile.default]
src= "src"
out= "out"
libs= ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@uniswap/permit2/=lib/permit2/",
  "@uniswap/universal-router/=lib/universal-router/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v2-core/=lib/v2-core/"
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/Ddiwbns2aYw5ZiPfwQJ-SM2Gw_DQwe1a"
reactive = "https://lasna-rpc.rnk.dev/"